---
- hosts: demoservers
  tasks:
  - name: Create destination directory
    sudo: yes
    command: mkdir -p /home/ec2-user/app-container

  - name: Change destination directory permissions
    sudo: yes
    command: chmod 777 /home/ec2-user/app-container

  - name: Copy Dockerfile and other files to server
    copy: src={{ item }} dest=/home/ec2-user/app-container mode=777
    with_items:
      - Dockerfile
      - init.sh

  - name: Remove container if already running
    sudo: yes
    docker:
      name: app
      image: app-img
      state: absent
    ignore_errors: yes

  - name: Remove previous image
    sudo: yes
    docker_image:
      name: app-img
      state: absent
    ignore_errors: yes

  - name: Build image
    sudo: yes
    docker_image:
      path: /home/ec2-user/app-container
      name: app-img
      state: build

  - name: Create container
    sudo: yes
    docker:
      name: app
      image: app-img
      state: started
      links:
      - "mongodb:mongodb"
      ports:
      - "3000:3000"
