---
- hosts: demoservers
  tasks:
  - name: Create destination directory
    sudo: yes
    command: mkdir -p /home/ec2-user/app-container

  - name: Make destination directory writable
    sudo: yes
    command: chmod 777 /home/ec2-user/app-container

  - name: Copy Dockerfile and other files to server
    copy: src={{ item }} dest=/home/ec2-user/app-container mode=777
    with_items:
      - Dockerfile
      - init.sh

  - name: Remove container if already running
    sudo: yes
    command: docker rm -f app
    ignore_errors: yes

  - name: Remove previous image
    sudo: yes
    command: docker rmi -f app-img
    ignore_errors: yes

  - name: Build image
    sudo: yes
    command: docker build -t app-img /home/ec2-user/app-container

  - name: Create container
    sudo: yes
    command: docker run -i -d -p 3000:3000 --link mongodb:mongodb --name app -t app-img
