---
- hosts: demoservers
  tasks:
  - name: Create destination directory
    sudo: yes
    command: mkdir -p /home/ec2-user/mongodb-container

  - name: Change destination directory permissions
    sudo: yes
    command: chmod 777 /home/ec2-user/mongodb-container

  - name: Copy Dockerfile and other files to server
    copy: src={{ item }} dest=/home/ec2-user/mongodb-container mode=777
    with_items:
      - Dockerfile
      - mongod.conf

  - name: Remove container if already running
    sudo: yes
    docker:
      name: mongodb
      image: mongo-img
      state: absent
    ignore_errors: yes

  - name: Remove previous image
    sudo: yes
    docker_image:
      name: mongo-img
      state: absent
    ignore_errors: yes

  - name: Build Docker image
    sudo: yes
    docker_image:
      path: /home/ec2-user/mongodb-container
      name: mongo-img
      state: build

  - name: Create Docker container
    sudo: yes
    docker:
      name: mongodb
      image: mongo-img
      state: started
      ports:
      - "0.0.0.0:27017:27017"
